(cl:defpackage rll_msgs-msg
  (:use )
  (:export
   "<JOBENVACTION>"
   "JOBENVACTION"
   "<JOBENVACTIONFEEDBACK>"
   "JOBENVACTIONFEEDBACK"
   "<JOBENVACTIONGOAL>"
   "JOBENVACTIONGOAL"
   "<JOBENVACTIONRESULT>"
   "JOBENVACTIONRESULT"
   "<JOBENVFEEDBACK>"
   "JOBENVFEEDBACK"
   "<JOBENVGOAL>"
   "JOBENVGOAL"
   "<JOBENVRESULT>"
   "JOBENVRESULT"
   "<JOBEXTRAFIELD>"
   "JOBEXTRAFIELD"
   "<JOBSTATUS>"
   "JOBSTATUS"
  ))

