; Auto-generated. Do not edit!


(cl:in-package rll_msgs-msg)


;//! \htmlinclude JobEnvGoal.msg.html

(cl:defclass <JobEnvGoal> (roslisp-msg-protocol:ros-message)
  ((authentication_secret
    :reader authentication_secret
    :initarg :authentication_secret
    :type cl:string
    :initform "")
   (client_ip_addr
    :reader client_ip_addr
    :initarg :client_ip_addr
    :type cl:string
    :initform ""))
)

(cl:defclass JobEnvGoal (<JobEnvGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <JobEnvGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'JobEnvGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name rll_msgs-msg:<JobEnvGoal> is deprecated: use rll_msgs-msg:JobEnvGoal instead.")))

(cl:ensure-generic-function 'authentication_secret-val :lambda-list '(m))
(cl:defmethod authentication_secret-val ((m <JobEnvGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader rll_msgs-msg:authentication_secret-val is deprecated.  Use rll_msgs-msg:authentication_secret instead.")
  (authentication_secret m))

(cl:ensure-generic-function 'client_ip_addr-val :lambda-list '(m))
(cl:defmethod client_ip_addr-val ((m <JobEnvGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader rll_msgs-msg:client_ip_addr-val is deprecated.  Use rll_msgs-msg:client_ip_addr instead.")
  (client_ip_addr m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <JobEnvGoal>) ostream)
  "Serializes a message object of type '<JobEnvGoal>"
  (cl:let ((__ros_str_len (cl:length (cl:slot-value msg 'authentication_secret))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_str_len) ostream))
  (cl:map cl:nil #'(cl:lambda (c) (cl:write-byte (cl:char-code c) ostream)) (cl:slot-value msg 'authentication_secret))
  (cl:let ((__ros_str_len (cl:length (cl:slot-value msg 'client_ip_addr))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_str_len) ostream))
  (cl:map cl:nil #'(cl:lambda (c) (cl:write-byte (cl:char-code c) ostream)) (cl:slot-value msg 'client_ip_addr))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <JobEnvGoal>) istream)
  "Deserializes a message object of type '<JobEnvGoal>"
    (cl:let ((__ros_str_len 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'authentication_secret) (cl:make-string __ros_str_len))
      (cl:dotimes (__ros_str_idx __ros_str_len msg)
        (cl:setf (cl:char (cl:slot-value msg 'authentication_secret) __ros_str_idx) (cl:code-char (cl:read-byte istream)))))
    (cl:let ((__ros_str_len 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'client_ip_addr) (cl:make-string __ros_str_len))
      (cl:dotimes (__ros_str_idx __ros_str_len msg)
        (cl:setf (cl:char (cl:slot-value msg 'client_ip_addr) __ros_str_idx) (cl:code-char (cl:read-byte istream)))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<JobEnvGoal>)))
  "Returns string type for a message object of type '<JobEnvGoal>"
  "rll_msgs/JobEnvGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'JobEnvGoal)))
  "Returns string type for a message object of type 'JobEnvGoal"
  "rll_msgs/JobEnvGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<JobEnvGoal>)))
  "Returns md5sum for a message object of type '<JobEnvGoal>"
  "8914a2dc1274b4dcf064150662370a1c")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'JobEnvGoal)))
  "Returns md5sum for a message object of type 'JobEnvGoal"
  "8914a2dc1274b4dcf064150662370a1c")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<JobEnvGoal>)))
  "Returns full string definition for message of type '<JobEnvGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%string authentication_secret~%string client_ip_addr~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'JobEnvGoal)))
  "Returns full string definition for message of type 'JobEnvGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%string authentication_secret~%string client_ip_addr~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <JobEnvGoal>))
  (cl:+ 0
     4 (cl:length (cl:slot-value msg 'authentication_secret))
     4 (cl:length (cl:slot-value msg 'client_ip_addr))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <JobEnvGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'JobEnvGoal
    (cl:cons ':authentication_secret (authentication_secret msg))
    (cl:cons ':client_ip_addr (client_ip_addr msg))
))
