// Generated by gencpp from file rll_msgs/GetJointValues.msg
// DO NOT EDIT!


#ifndef RLL_MSGS_MESSAGE_GETJOINTVALUES_H
#define RLL_MSGS_MESSAGE_GETJOINTVALUES_H

#include <ros/service_traits.h>


#include <rll_msgs/GetJointValuesRequest.h>
#include <rll_msgs/GetJointValuesResponse.h>


namespace rll_msgs
{

struct GetJointValues
{

typedef GetJointValuesRequest Request;
typedef GetJointValuesResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetJointValues
} // namespace rll_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rll_msgs::GetJointValues > {
  static const char* value()
  {
    return "8e5a3555469b4e8d3327599e7f25c1a4";
  }

  static const char* value(const ::rll_msgs::GetJointValues&) { return value(); }
};

template<>
struct DataType< ::rll_msgs::GetJointValues > {
  static const char* value()
  {
    return "rll_msgs/GetJointValues";
  }

  static const char* value(const ::rll_msgs::GetJointValues&) { return value(); }
};


// service_traits::MD5Sum< ::rll_msgs::GetJointValuesRequest> should match
// service_traits::MD5Sum< ::rll_msgs::GetJointValues >
template<>
struct MD5Sum< ::rll_msgs::GetJointValuesRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rll_msgs::GetJointValues >::value();
  }
  static const char* value(const ::rll_msgs::GetJointValuesRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rll_msgs::GetJointValuesRequest> should match
// service_traits::DataType< ::rll_msgs::GetJointValues >
template<>
struct DataType< ::rll_msgs::GetJointValuesRequest>
{
  static const char* value()
  {
    return DataType< ::rll_msgs::GetJointValues >::value();
  }
  static const char* value(const ::rll_msgs::GetJointValuesRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rll_msgs::GetJointValuesResponse> should match
// service_traits::MD5Sum< ::rll_msgs::GetJointValues >
template<>
struct MD5Sum< ::rll_msgs::GetJointValuesResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rll_msgs::GetJointValues >::value();
  }
  static const char* value(const ::rll_msgs::GetJointValuesResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rll_msgs::GetJointValuesResponse> should match
// service_traits::DataType< ::rll_msgs::GetJointValues >
template<>
struct DataType< ::rll_msgs::GetJointValuesResponse>
{
  static const char* value()
  {
    return DataType< ::rll_msgs::GetJointValues >::value();
  }
  static const char* value(const ::rll_msgs::GetJointValuesResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // RLL_MSGS_MESSAGE_GETJOINTVALUES_H
