// Generated by gencpp from file rll_msgs/GetPoseResponse.msg
// DO NOT EDIT!


#ifndef RLL_MSGS_MESSAGE_GETPOSERESPONSE_H
#define RLL_MSGS_MESSAGE_GETPOSERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose.h>

namespace rll_msgs
{
template <class ContainerAllocator>
struct GetPoseResponse_
{
  typedef GetPoseResponse_<ContainerAllocator> Type;

  GetPoseResponse_()
    : success(false)
    , error_code(0)
    , pose()
    , arm_angle(0.0)
    , config(0)  {
    }
  GetPoseResponse_(const ContainerAllocator& _alloc)
    : success(false)
    , error_code(0)
    , pose(_alloc)
    , arm_angle(0.0)
    , config(0)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;

   typedef uint8_t _error_code_type;
  _error_code_type error_code;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _pose_type;
  _pose_type pose;

   typedef double _arm_angle_type;
  _arm_angle_type arm_angle;

   typedef uint8_t _config_type;
  _config_type config;





  typedef boost::shared_ptr< ::rll_msgs::GetPoseResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rll_msgs::GetPoseResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetPoseResponse_

typedef ::rll_msgs::GetPoseResponse_<std::allocator<void> > GetPoseResponse;

typedef boost::shared_ptr< ::rll_msgs::GetPoseResponse > GetPoseResponsePtr;
typedef boost::shared_ptr< ::rll_msgs::GetPoseResponse const> GetPoseResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rll_msgs::GetPoseResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rll_msgs::GetPoseResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rll_msgs::GetPoseResponse_<ContainerAllocator1> & lhs, const ::rll_msgs::GetPoseResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success &&
    lhs.error_code == rhs.error_code &&
    lhs.pose == rhs.pose &&
    lhs.arm_angle == rhs.arm_angle &&
    lhs.config == rhs.config;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rll_msgs::GetPoseResponse_<ContainerAllocator1> & lhs, const ::rll_msgs::GetPoseResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rll_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::rll_msgs::GetPoseResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rll_msgs::GetPoseResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rll_msgs::GetPoseResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rll_msgs::GetPoseResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rll_msgs::GetPoseResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rll_msgs::GetPoseResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rll_msgs::GetPoseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "00cfbf912d5d5d335e09a4e695a7bfef";
  }

  static const char* value(const ::rll_msgs::GetPoseResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x00cfbf912d5d5d33ULL;
  static const uint64_t static_value2 = 0x5e09a4e695a7bfefULL;
};

template<class ContainerAllocator>
struct DataType< ::rll_msgs::GetPoseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rll_msgs/GetPoseResponse";
  }

  static const char* value(const ::rll_msgs::GetPoseResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rll_msgs::GetPoseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n"
"uint8 error_code\n"
"geometry_msgs/Pose pose\n"
"float64 arm_angle\n"
"uint8 config\n"
"\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::rll_msgs::GetPoseResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rll_msgs::GetPoseResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
      stream.next(m.error_code);
      stream.next(m.pose);
      stream.next(m.arm_angle);
      stream.next(m.config);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetPoseResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rll_msgs::GetPoseResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rll_msgs::GetPoseResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    s << indent << "error_code: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.error_code);
    s << indent << "pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.pose);
    s << indent << "arm_angle: ";
    Printer<double>::stream(s, indent + "  ", v.arm_angle);
    s << indent << "config: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.config);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RLL_MSGS_MESSAGE_GETPOSERESPONSE_H
