// Generated by gencpp from file rll_msgs/GetPose.msg
// DO NOT EDIT!


#ifndef RLL_MSGS_MESSAGE_GETPOSE_H
#define RLL_MSGS_MESSAGE_GETPOSE_H

#include <ros/service_traits.h>


#include <rll_msgs/GetPoseRequest.h>
#include <rll_msgs/GetPoseResponse.h>


namespace rll_msgs
{

struct GetPose
{

typedef GetPoseRequest Request;
typedef GetPoseResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetPose
} // namespace rll_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rll_msgs::GetPose > {
  static const char* value()
  {
    return "00cfbf912d5d5d335e09a4e695a7bfef";
  }

  static const char* value(const ::rll_msgs::GetPose&) { return value(); }
};

template<>
struct DataType< ::rll_msgs::GetPose > {
  static const char* value()
  {
    return "rll_msgs/GetPose";
  }

  static const char* value(const ::rll_msgs::GetPose&) { return value(); }
};


// service_traits::MD5Sum< ::rll_msgs::GetPoseRequest> should match
// service_traits::MD5Sum< ::rll_msgs::GetPose >
template<>
struct MD5Sum< ::rll_msgs::GetPoseRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rll_msgs::GetPose >::value();
  }
  static const char* value(const ::rll_msgs::GetPoseRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rll_msgs::GetPoseRequest> should match
// service_traits::DataType< ::rll_msgs::GetPose >
template<>
struct DataType< ::rll_msgs::GetPoseRequest>
{
  static const char* value()
  {
    return DataType< ::rll_msgs::GetPose >::value();
  }
  static const char* value(const ::rll_msgs::GetPoseRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rll_msgs::GetPoseResponse> should match
// service_traits::MD5Sum< ::rll_msgs::GetPose >
template<>
struct MD5Sum< ::rll_msgs::GetPoseResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rll_msgs::GetPose >::value();
  }
  static const char* value(const ::rll_msgs::GetPoseResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rll_msgs::GetPoseResponse> should match
// service_traits::DataType< ::rll_msgs::GetPose >
template<>
struct DataType< ::rll_msgs::GetPoseResponse>
{
  static const char* value()
  {
    return DataType< ::rll_msgs::GetPose >::value();
  }
  static const char* value(const ::rll_msgs::GetPoseResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // RLL_MSGS_MESSAGE_GETPOSE_H
