// Generated by gencpp from file rll_msgs/MovePTPResponse.msg
// DO NOT EDIT!


#ifndef RLL_MSGS_MESSAGE_MOVEPTPRESPONSE_H
#define RLL_MSGS_MESSAGE_MOVEPTPRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rll_msgs
{
template <class ContainerAllocator>
struct MovePTPResponse_
{
  typedef MovePTPResponse_<ContainerAllocator> Type;

  MovePTPResponse_()
    : success(false)
    , error_code(0)  {
    }
  MovePTPResponse_(const ContainerAllocator& _alloc)
    : success(false)
    , error_code(0)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;

   typedef uint8_t _error_code_type;
  _error_code_type error_code;





  typedef boost::shared_ptr< ::rll_msgs::MovePTPResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rll_msgs::MovePTPResponse_<ContainerAllocator> const> ConstPtr;

}; // struct MovePTPResponse_

typedef ::rll_msgs::MovePTPResponse_<std::allocator<void> > MovePTPResponse;

typedef boost::shared_ptr< ::rll_msgs::MovePTPResponse > MovePTPResponsePtr;
typedef boost::shared_ptr< ::rll_msgs::MovePTPResponse const> MovePTPResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rll_msgs::MovePTPResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rll_msgs::MovePTPResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rll_msgs::MovePTPResponse_<ContainerAllocator1> & lhs, const ::rll_msgs::MovePTPResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success &&
    lhs.error_code == rhs.error_code;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rll_msgs::MovePTPResponse_<ContainerAllocator1> & lhs, const ::rll_msgs::MovePTPResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rll_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::rll_msgs::MovePTPResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rll_msgs::MovePTPResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rll_msgs::MovePTPResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rll_msgs::MovePTPResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rll_msgs::MovePTPResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rll_msgs::MovePTPResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rll_msgs::MovePTPResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e64e855da06d239f5ca2100b107659ac";
  }

  static const char* value(const ::rll_msgs::MovePTPResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe64e855da06d239fULL;
  static const uint64_t static_value2 = 0x5ca2100b107659acULL;
};

template<class ContainerAllocator>
struct DataType< ::rll_msgs::MovePTPResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rll_msgs/MovePTPResponse";
  }

  static const char* value(const ::rll_msgs::MovePTPResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rll_msgs::MovePTPResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n"
"uint8 error_code\n"
"\n"
;
  }

  static const char* value(const ::rll_msgs::MovePTPResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rll_msgs::MovePTPResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
      stream.next(m.error_code);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MovePTPResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rll_msgs::MovePTPResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rll_msgs::MovePTPResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    s << indent << "error_code: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.error_code);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RLL_MSGS_MESSAGE_MOVEPTPRESPONSE_H
