// Generated by gencpp from file rll_msgs/MoveRandomResponse.msg
// DO NOT EDIT!


#ifndef RLL_MSGS_MESSAGE_MOVERANDOMRESPONSE_H
#define RLL_MSGS_MESSAGE_MOVERANDOMRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose.h>

namespace rll_msgs
{
template <class ContainerAllocator>
struct MoveRandomResponse_
{
  typedef MoveRandomResponse_<ContainerAllocator> Type;

  MoveRandomResponse_()
    : pose()
    , success(false)
    , error_code(0)  {
    }
  MoveRandomResponse_(const ContainerAllocator& _alloc)
    : pose(_alloc)
    , success(false)
    , error_code(0)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _pose_type;
  _pose_type pose;

   typedef uint8_t _success_type;
  _success_type success;

   typedef uint8_t _error_code_type;
  _error_code_type error_code;





  typedef boost::shared_ptr< ::rll_msgs::MoveRandomResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rll_msgs::MoveRandomResponse_<ContainerAllocator> const> ConstPtr;

}; // struct MoveRandomResponse_

typedef ::rll_msgs::MoveRandomResponse_<std::allocator<void> > MoveRandomResponse;

typedef boost::shared_ptr< ::rll_msgs::MoveRandomResponse > MoveRandomResponsePtr;
typedef boost::shared_ptr< ::rll_msgs::MoveRandomResponse const> MoveRandomResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rll_msgs::MoveRandomResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rll_msgs::MoveRandomResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rll_msgs::MoveRandomResponse_<ContainerAllocator1> & lhs, const ::rll_msgs::MoveRandomResponse_<ContainerAllocator2> & rhs)
{
  return lhs.pose == rhs.pose &&
    lhs.success == rhs.success &&
    lhs.error_code == rhs.error_code;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rll_msgs::MoveRandomResponse_<ContainerAllocator1> & lhs, const ::rll_msgs::MoveRandomResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rll_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::rll_msgs::MoveRandomResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rll_msgs::MoveRandomResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rll_msgs::MoveRandomResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rll_msgs::MoveRandomResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rll_msgs::MoveRandomResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rll_msgs::MoveRandomResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rll_msgs::MoveRandomResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b292fbfae6ae3594727e822d1d4ce5a2";
  }

  static const char* value(const ::rll_msgs::MoveRandomResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb292fbfae6ae3594ULL;
  static const uint64_t static_value2 = 0x727e822d1d4ce5a2ULL;
};

template<class ContainerAllocator>
struct DataType< ::rll_msgs::MoveRandomResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rll_msgs/MoveRandomResponse";
  }

  static const char* value(const ::rll_msgs::MoveRandomResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rll_msgs::MoveRandomResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Pose pose\n"
"bool success\n"
"uint8 error_code\n"
"\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::rll_msgs::MoveRandomResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rll_msgs::MoveRandomResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pose);
      stream.next(m.success);
      stream.next(m.error_code);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MoveRandomResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rll_msgs::MoveRandomResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rll_msgs::MoveRandomResponse_<ContainerAllocator>& v)
  {
    s << indent << "pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.pose);
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    s << indent << "error_code: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.error_code);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RLL_MSGS_MESSAGE_MOVERANDOMRESPONSE_H
