// Generated by gencpp from file rll_msgs/MoveRandom.msg
// DO NOT EDIT!


#ifndef RLL_MSGS_MESSAGE_MOVERANDOM_H
#define RLL_MSGS_MESSAGE_MOVERANDOM_H

#include <ros/service_traits.h>


#include <rll_msgs/MoveRandomRequest.h>
#include <rll_msgs/MoveRandomResponse.h>


namespace rll_msgs
{

struct MoveRandom
{

typedef MoveRandomRequest Request;
typedef MoveRandomResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MoveRandom
} // namespace rll_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rll_msgs::MoveRandom > {
  static const char* value()
  {
    return "b292fbfae6ae3594727e822d1d4ce5a2";
  }

  static const char* value(const ::rll_msgs::MoveRandom&) { return value(); }
};

template<>
struct DataType< ::rll_msgs::MoveRandom > {
  static const char* value()
  {
    return "rll_msgs/MoveRandom";
  }

  static const char* value(const ::rll_msgs::MoveRandom&) { return value(); }
};


// service_traits::MD5Sum< ::rll_msgs::MoveRandomRequest> should match
// service_traits::MD5Sum< ::rll_msgs::MoveRandom >
template<>
struct MD5Sum< ::rll_msgs::MoveRandomRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rll_msgs::MoveRandom >::value();
  }
  static const char* value(const ::rll_msgs::MoveRandomRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rll_msgs::MoveRandomRequest> should match
// service_traits::DataType< ::rll_msgs::MoveRandom >
template<>
struct DataType< ::rll_msgs::MoveRandomRequest>
{
  static const char* value()
  {
    return DataType< ::rll_msgs::MoveRandom >::value();
  }
  static const char* value(const ::rll_msgs::MoveRandomRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rll_msgs::MoveRandomResponse> should match
// service_traits::MD5Sum< ::rll_msgs::MoveRandom >
template<>
struct MD5Sum< ::rll_msgs::MoveRandomResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rll_msgs::MoveRandom >::value();
  }
  static const char* value(const ::rll_msgs::MoveRandomResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rll_msgs::MoveRandomResponse> should match
// service_traits::DataType< ::rll_msgs::MoveRandom >
template<>
struct DataType< ::rll_msgs::MoveRandomResponse>
{
  static const char* value()
  {
    return DataType< ::rll_msgs::MoveRandom >::value();
  }
  static const char* value(const ::rll_msgs::MoveRandomResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // RLL_MSGS_MESSAGE_MOVERANDOM_H
