// Generated by gencpp from file rll_msgs/MovePTPArmangle.msg
// DO NOT EDIT!


#ifndef RLL_MSGS_MESSAGE_MOVEPTPARMANGLE_H
#define RLL_MSGS_MESSAGE_MOVEPTPARMANGLE_H

#include <ros/service_traits.h>


#include <rll_msgs/MovePTPArmangleRequest.h>
#include <rll_msgs/MovePTPArmangleResponse.h>


namespace rll_msgs
{

struct MovePTPArmangle
{

typedef MovePTPArmangleRequest Request;
typedef MovePTPArmangleResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MovePTPArmangle
} // namespace rll_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rll_msgs::MovePTPArmangle > {
  static const char* value()
  {
    return "120f4f54a5ecc4177ce4f86f46f94f5d";
  }

  static const char* value(const ::rll_msgs::MovePTPArmangle&) { return value(); }
};

template<>
struct DataType< ::rll_msgs::MovePTPArmangle > {
  static const char* value()
  {
    return "rll_msgs/MovePTPArmangle";
  }

  static const char* value(const ::rll_msgs::MovePTPArmangle&) { return value(); }
};


// service_traits::MD5Sum< ::rll_msgs::MovePTPArmangleRequest> should match
// service_traits::MD5Sum< ::rll_msgs::MovePTPArmangle >
template<>
struct MD5Sum< ::rll_msgs::MovePTPArmangleRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rll_msgs::MovePTPArmangle >::value();
  }
  static const char* value(const ::rll_msgs::MovePTPArmangleRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rll_msgs::MovePTPArmangleRequest> should match
// service_traits::DataType< ::rll_msgs::MovePTPArmangle >
template<>
struct DataType< ::rll_msgs::MovePTPArmangleRequest>
{
  static const char* value()
  {
    return DataType< ::rll_msgs::MovePTPArmangle >::value();
  }
  static const char* value(const ::rll_msgs::MovePTPArmangleRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rll_msgs::MovePTPArmangleResponse> should match
// service_traits::MD5Sum< ::rll_msgs::MovePTPArmangle >
template<>
struct MD5Sum< ::rll_msgs::MovePTPArmangleResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rll_msgs::MovePTPArmangle >::value();
  }
  static const char* value(const ::rll_msgs::MovePTPArmangleResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rll_msgs::MovePTPArmangleResponse> should match
// service_traits::DataType< ::rll_msgs::MovePTPArmangle >
template<>
struct DataType< ::rll_msgs::MovePTPArmangleResponse>
{
  static const char* value()
  {
    return DataType< ::rll_msgs::MovePTPArmangle >::value();
  }
  static const char* value(const ::rll_msgs::MovePTPArmangleResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // RLL_MSGS_MESSAGE_MOVEPTPARMANGLE_H
