// Generated by gencpp from file rll_msgs/MoveLinArmangle.msg
// DO NOT EDIT!


#ifndef RLL_MSGS_MESSAGE_MOVELINARMANGLE_H
#define RLL_MSGS_MESSAGE_MOVELINARMANGLE_H

#include <ros/service_traits.h>


#include <rll_msgs/MoveLinArmangleRequest.h>
#include <rll_msgs/MoveLinArmangleResponse.h>


namespace rll_msgs
{

struct MoveLinArmangle
{

typedef MoveLinArmangleRequest Request;
typedef MoveLinArmangleResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MoveLinArmangle
} // namespace rll_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rll_msgs::MoveLinArmangle > {
  static const char* value()
  {
    return "74e55c617279aa58663455a6351ca165";
  }

  static const char* value(const ::rll_msgs::MoveLinArmangle&) { return value(); }
};

template<>
struct DataType< ::rll_msgs::MoveLinArmangle > {
  static const char* value()
  {
    return "rll_msgs/MoveLinArmangle";
  }

  static const char* value(const ::rll_msgs::MoveLinArmangle&) { return value(); }
};


// service_traits::MD5Sum< ::rll_msgs::MoveLinArmangleRequest> should match
// service_traits::MD5Sum< ::rll_msgs::MoveLinArmangle >
template<>
struct MD5Sum< ::rll_msgs::MoveLinArmangleRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rll_msgs::MoveLinArmangle >::value();
  }
  static const char* value(const ::rll_msgs::MoveLinArmangleRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rll_msgs::MoveLinArmangleRequest> should match
// service_traits::DataType< ::rll_msgs::MoveLinArmangle >
template<>
struct DataType< ::rll_msgs::MoveLinArmangleRequest>
{
  static const char* value()
  {
    return DataType< ::rll_msgs::MoveLinArmangle >::value();
  }
  static const char* value(const ::rll_msgs::MoveLinArmangleRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rll_msgs::MoveLinArmangleResponse> should match
// service_traits::MD5Sum< ::rll_msgs::MoveLinArmangle >
template<>
struct MD5Sum< ::rll_msgs::MoveLinArmangleResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rll_msgs::MoveLinArmangle >::value();
  }
  static const char* value(const ::rll_msgs::MoveLinArmangleResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rll_msgs::MoveLinArmangleResponse> should match
// service_traits::DataType< ::rll_msgs::MoveLinArmangle >
template<>
struct DataType< ::rll_msgs::MoveLinArmangleResponse>
{
  static const char* value()
  {
    return DataType< ::rll_msgs::MoveLinArmangle >::value();
  }
  static const char* value(const ::rll_msgs::MoveLinArmangleResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // RLL_MSGS_MESSAGE_MOVELINARMANGLE_H
