// Generated by gencpp from file rll_msgs/MoveLinArmangleRequest.msg
// DO NOT EDIT!


#ifndef RLL_MSGS_MESSAGE_MOVELINARMANGLEREQUEST_H
#define RLL_MSGS_MESSAGE_MOVELINARMANGLEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose.h>

namespace rll_msgs
{
template <class ContainerAllocator>
struct MoveLinArmangleRequest_
{
  typedef MoveLinArmangleRequest_<ContainerAllocator> Type;

  MoveLinArmangleRequest_()
    : pose()
    , arm_angle(0.0)
    , direction(false)  {
    }
  MoveLinArmangleRequest_(const ContainerAllocator& _alloc)
    : pose(_alloc)
    , arm_angle(0.0)
    , direction(false)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _pose_type;
  _pose_type pose;

   typedef double _arm_angle_type;
  _arm_angle_type arm_angle;

   typedef uint8_t _direction_type;
  _direction_type direction;





  typedef boost::shared_ptr< ::rll_msgs::MoveLinArmangleRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rll_msgs::MoveLinArmangleRequest_<ContainerAllocator> const> ConstPtr;

}; // struct MoveLinArmangleRequest_

typedef ::rll_msgs::MoveLinArmangleRequest_<std::allocator<void> > MoveLinArmangleRequest;

typedef boost::shared_ptr< ::rll_msgs::MoveLinArmangleRequest > MoveLinArmangleRequestPtr;
typedef boost::shared_ptr< ::rll_msgs::MoveLinArmangleRequest const> MoveLinArmangleRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rll_msgs::MoveLinArmangleRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rll_msgs::MoveLinArmangleRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rll_msgs::MoveLinArmangleRequest_<ContainerAllocator1> & lhs, const ::rll_msgs::MoveLinArmangleRequest_<ContainerAllocator2> & rhs)
{
  return lhs.pose == rhs.pose &&
    lhs.arm_angle == rhs.arm_angle &&
    lhs.direction == rhs.direction;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rll_msgs::MoveLinArmangleRequest_<ContainerAllocator1> & lhs, const ::rll_msgs::MoveLinArmangleRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rll_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::rll_msgs::MoveLinArmangleRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rll_msgs::MoveLinArmangleRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rll_msgs::MoveLinArmangleRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rll_msgs::MoveLinArmangleRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rll_msgs::MoveLinArmangleRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rll_msgs::MoveLinArmangleRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rll_msgs::MoveLinArmangleRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1d1ed43712b93e277b1e746f8d056445";
  }

  static const char* value(const ::rll_msgs::MoveLinArmangleRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1d1ed43712b93e27ULL;
  static const uint64_t static_value2 = 0x7b1e746f8d056445ULL;
};

template<class ContainerAllocator>
struct DataType< ::rll_msgs::MoveLinArmangleRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rll_msgs/MoveLinArmangleRequest";
  }

  static const char* value(const ::rll_msgs::MoveLinArmangleRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rll_msgs::MoveLinArmangleRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Pose pose\n"
"float64 arm_angle\n"
"bool direction\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::rll_msgs::MoveLinArmangleRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rll_msgs::MoveLinArmangleRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pose);
      stream.next(m.arm_angle);
      stream.next(m.direction);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MoveLinArmangleRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rll_msgs::MoveLinArmangleRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rll_msgs::MoveLinArmangleRequest_<ContainerAllocator>& v)
  {
    s << indent << "pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.pose);
    s << indent << "arm_angle: ";
    Printer<double>::stream(s, indent + "  ", v.arm_angle);
    s << indent << "direction: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.direction);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RLL_MSGS_MESSAGE_MOVELINARMANGLEREQUEST_H
