// Generated by gencpp from file rll_planning_project/GetStartGoalRequest.msg
// DO NOT EDIT!


#ifndef RLL_PLANNING_PROJECT_MESSAGE_GETSTARTGOALREQUEST_H
#define RLL_PLANNING_PROJECT_MESSAGE_GETSTARTGOALREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rll_planning_project
{
template <class ContainerAllocator>
struct GetStartGoalRequest_
{
  typedef GetStartGoalRequest_<ContainerAllocator> Type;

  GetStartGoalRequest_()
    {
    }
  GetStartGoalRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::rll_planning_project::GetStartGoalRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rll_planning_project::GetStartGoalRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GetStartGoalRequest_

typedef ::rll_planning_project::GetStartGoalRequest_<std::allocator<void> > GetStartGoalRequest;

typedef boost::shared_ptr< ::rll_planning_project::GetStartGoalRequest > GetStartGoalRequestPtr;
typedef boost::shared_ptr< ::rll_planning_project::GetStartGoalRequest const> GetStartGoalRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rll_planning_project::GetStartGoalRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rll_planning_project::GetStartGoalRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace rll_planning_project

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::rll_planning_project::GetStartGoalRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rll_planning_project::GetStartGoalRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rll_planning_project::GetStartGoalRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rll_planning_project::GetStartGoalRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rll_planning_project::GetStartGoalRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rll_planning_project::GetStartGoalRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rll_planning_project::GetStartGoalRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::rll_planning_project::GetStartGoalRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::rll_planning_project::GetStartGoalRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rll_planning_project/GetStartGoalRequest";
  }

  static const char* value(const ::rll_planning_project::GetStartGoalRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rll_planning_project::GetStartGoalRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::rll_planning_project::GetStartGoalRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rll_planning_project::GetStartGoalRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetStartGoalRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rll_planning_project::GetStartGoalRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::rll_planning_project::GetStartGoalRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // RLL_PLANNING_PROJECT_MESSAGE_GETSTARTGOALREQUEST_H
