// Generated by gencpp from file rll_planning_project/GetStartGoal.msg
// DO NOT EDIT!


#ifndef RLL_PLANNING_PROJECT_MESSAGE_GETSTARTGOAL_H
#define RLL_PLANNING_PROJECT_MESSAGE_GETSTARTGOAL_H

#include <ros/service_traits.h>


#include <rll_planning_project/GetStartGoalRequest.h>
#include <rll_planning_project/GetStartGoalResponse.h>


namespace rll_planning_project
{

struct GetStartGoal
{

typedef GetStartGoalRequest Request;
typedef GetStartGoalResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetStartGoal
} // namespace rll_planning_project


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rll_planning_project::GetStartGoal > {
  static const char* value()
  {
    return "20f5244415b7ff944aeb9f4f84fb11ce";
  }

  static const char* value(const ::rll_planning_project::GetStartGoal&) { return value(); }
};

template<>
struct DataType< ::rll_planning_project::GetStartGoal > {
  static const char* value()
  {
    return "rll_planning_project/GetStartGoal";
  }

  static const char* value(const ::rll_planning_project::GetStartGoal&) { return value(); }
};


// service_traits::MD5Sum< ::rll_planning_project::GetStartGoalRequest> should match
// service_traits::MD5Sum< ::rll_planning_project::GetStartGoal >
template<>
struct MD5Sum< ::rll_planning_project::GetStartGoalRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rll_planning_project::GetStartGoal >::value();
  }
  static const char* value(const ::rll_planning_project::GetStartGoalRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rll_planning_project::GetStartGoalRequest> should match
// service_traits::DataType< ::rll_planning_project::GetStartGoal >
template<>
struct DataType< ::rll_planning_project::GetStartGoalRequest>
{
  static const char* value()
  {
    return DataType< ::rll_planning_project::GetStartGoal >::value();
  }
  static const char* value(const ::rll_planning_project::GetStartGoalRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rll_planning_project::GetStartGoalResponse> should match
// service_traits::MD5Sum< ::rll_planning_project::GetStartGoal >
template<>
struct MD5Sum< ::rll_planning_project::GetStartGoalResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rll_planning_project::GetStartGoal >::value();
  }
  static const char* value(const ::rll_planning_project::GetStartGoalResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rll_planning_project::GetStartGoalResponse> should match
// service_traits::DataType< ::rll_planning_project::GetStartGoal >
template<>
struct DataType< ::rll_planning_project::GetStartGoalResponse>
{
  static const char* value()
  {
    return DataType< ::rll_planning_project::GetStartGoal >::value();
  }
  static const char* value(const ::rll_planning_project::GetStartGoalResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // RLL_PLANNING_PROJECT_MESSAGE_GETSTARTGOAL_H
