// Generated by gencpp from file rll_planning_project/GetStartGoalResponse.msg
// DO NOT EDIT!


#ifndef RLL_PLANNING_PROJECT_MESSAGE_GETSTARTGOALRESPONSE_H
#define RLL_PLANNING_PROJECT_MESSAGE_GETSTARTGOALRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose2D.h>
#include <geometry_msgs/Pose2D.h>

namespace rll_planning_project
{
template <class ContainerAllocator>
struct GetStartGoalResponse_
{
  typedef GetStartGoalResponse_<ContainerAllocator> Type;

  GetStartGoalResponse_()
    : success(false)
    , error_code(0)
    , start()
    , goal()  {
    }
  GetStartGoalResponse_(const ContainerAllocator& _alloc)
    : success(false)
    , error_code(0)
    , start(_alloc)
    , goal(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;

   typedef uint8_t _error_code_type;
  _error_code_type error_code;

   typedef  ::geometry_msgs::Pose2D_<ContainerAllocator>  _start_type;
  _start_type start;

   typedef  ::geometry_msgs::Pose2D_<ContainerAllocator>  _goal_type;
  _goal_type goal;





  typedef boost::shared_ptr< ::rll_planning_project::GetStartGoalResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rll_planning_project::GetStartGoalResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetStartGoalResponse_

typedef ::rll_planning_project::GetStartGoalResponse_<std::allocator<void> > GetStartGoalResponse;

typedef boost::shared_ptr< ::rll_planning_project::GetStartGoalResponse > GetStartGoalResponsePtr;
typedef boost::shared_ptr< ::rll_planning_project::GetStartGoalResponse const> GetStartGoalResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rll_planning_project::GetStartGoalResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rll_planning_project::GetStartGoalResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rll_planning_project::GetStartGoalResponse_<ContainerAllocator1> & lhs, const ::rll_planning_project::GetStartGoalResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success &&
    lhs.error_code == rhs.error_code &&
    lhs.start == rhs.start &&
    lhs.goal == rhs.goal;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rll_planning_project::GetStartGoalResponse_<ContainerAllocator1> & lhs, const ::rll_planning_project::GetStartGoalResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rll_planning_project

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::rll_planning_project::GetStartGoalResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rll_planning_project::GetStartGoalResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rll_planning_project::GetStartGoalResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rll_planning_project::GetStartGoalResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rll_planning_project::GetStartGoalResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rll_planning_project::GetStartGoalResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rll_planning_project::GetStartGoalResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "20f5244415b7ff944aeb9f4f84fb11ce";
  }

  static const char* value(const ::rll_planning_project::GetStartGoalResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x20f5244415b7ff94ULL;
  static const uint64_t static_value2 = 0x4aeb9f4f84fb11ceULL;
};

template<class ContainerAllocator>
struct DataType< ::rll_planning_project::GetStartGoalResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rll_planning_project/GetStartGoalResponse";
  }

  static const char* value(const ::rll_planning_project::GetStartGoalResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rll_planning_project::GetStartGoalResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n"
"uint8 error_code\n"
"geometry_msgs/Pose2D start\n"
"geometry_msgs/Pose2D goal\n"
"\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose2D\n"
"# Deprecated\n"
"# Please use the full 3D pose.\n"
"\n"
"# In general our recommendation is to use a full 3D representation of everything and for 2D specific applications make the appropriate projections into the plane for their calculations but optimally will preserve the 3D information during processing.\n"
"\n"
"# If we have parallel copies of 2D datatypes every UI and other pipeline will end up needing to have dual interfaces to plot everything. And you will end up with not being able to use 3D tools for 2D use cases even if they're completely valid, as you'd have to reimplement it with different inputs and outputs. It's not particularly hard to plot the 2D pose or compute the yaw error for the Pose message and there are already tools and libraries that can do this for you.\n"
"\n"
"\n"
"# This expresses a position and orientation on a 2D manifold.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 theta\n"
;
  }

  static const char* value(const ::rll_planning_project::GetStartGoalResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rll_planning_project::GetStartGoalResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
      stream.next(m.error_code);
      stream.next(m.start);
      stream.next(m.goal);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetStartGoalResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rll_planning_project::GetStartGoalResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rll_planning_project::GetStartGoalResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    s << indent << "error_code: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.error_code);
    s << indent << "start: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose2D_<ContainerAllocator> >::stream(s, indent + "  ", v.start);
    s << indent << "goal: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose2D_<ContainerAllocator> >::stream(s, indent + "  ", v.goal);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RLL_PLANNING_PROJECT_MESSAGE_GETSTARTGOALRESPONSE_H
