// Generated by gencpp from file rll_planning_project/MoveResponse.msg
// DO NOT EDIT!


#ifndef RLL_PLANNING_PROJECT_MESSAGE_MOVERESPONSE_H
#define RLL_PLANNING_PROJECT_MESSAGE_MOVERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rll_planning_project
{
template <class ContainerAllocator>
struct MoveResponse_
{
  typedef MoveResponse_<ContainerAllocator> Type;

  MoveResponse_()
    : success(false)
    , error_code(0)  {
    }
  MoveResponse_(const ContainerAllocator& _alloc)
    : success(false)
    , error_code(0)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;

   typedef uint8_t _error_code_type;
  _error_code_type error_code;





  typedef boost::shared_ptr< ::rll_planning_project::MoveResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rll_planning_project::MoveResponse_<ContainerAllocator> const> ConstPtr;

}; // struct MoveResponse_

typedef ::rll_planning_project::MoveResponse_<std::allocator<void> > MoveResponse;

typedef boost::shared_ptr< ::rll_planning_project::MoveResponse > MoveResponsePtr;
typedef boost::shared_ptr< ::rll_planning_project::MoveResponse const> MoveResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rll_planning_project::MoveResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rll_planning_project::MoveResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rll_planning_project::MoveResponse_<ContainerAllocator1> & lhs, const ::rll_planning_project::MoveResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success &&
    lhs.error_code == rhs.error_code;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rll_planning_project::MoveResponse_<ContainerAllocator1> & lhs, const ::rll_planning_project::MoveResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rll_planning_project

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::rll_planning_project::MoveResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rll_planning_project::MoveResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rll_planning_project::MoveResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rll_planning_project::MoveResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rll_planning_project::MoveResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rll_planning_project::MoveResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rll_planning_project::MoveResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e64e855da06d239f5ca2100b107659ac";
  }

  static const char* value(const ::rll_planning_project::MoveResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe64e855da06d239fULL;
  static const uint64_t static_value2 = 0x5ca2100b107659acULL;
};

template<class ContainerAllocator>
struct DataType< ::rll_planning_project::MoveResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rll_planning_project/MoveResponse";
  }

  static const char* value(const ::rll_planning_project::MoveResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rll_planning_project::MoveResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n"
"uint8 error_code\n"
;
  }

  static const char* value(const ::rll_planning_project::MoveResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rll_planning_project::MoveResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
      stream.next(m.error_code);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MoveResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rll_planning_project::MoveResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rll_planning_project::MoveResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    s << indent << "error_code: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.error_code);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RLL_PLANNING_PROJECT_MESSAGE_MOVERESPONSE_H
