// Auto-generated. Do not edit!

// (in-package rll_msgs.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class JobEnvGoal {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.authentication_secret = null;
      this.client_ip_addr = null;
    }
    else {
      if (initObj.hasOwnProperty('authentication_secret')) {
        this.authentication_secret = initObj.authentication_secret
      }
      else {
        this.authentication_secret = '';
      }
      if (initObj.hasOwnProperty('client_ip_addr')) {
        this.client_ip_addr = initObj.client_ip_addr
      }
      else {
        this.client_ip_addr = '';
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type JobEnvGoal
    // Serialize message field [authentication_secret]
    bufferOffset = _serializer.string(obj.authentication_secret, buffer, bufferOffset);
    // Serialize message field [client_ip_addr]
    bufferOffset = _serializer.string(obj.client_ip_addr, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type JobEnvGoal
    let len;
    let data = new JobEnvGoal(null);
    // Deserialize message field [authentication_secret]
    data.authentication_secret = _deserializer.string(buffer, bufferOffset);
    // Deserialize message field [client_ip_addr]
    data.client_ip_addr = _deserializer.string(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    let length = 0;
    length += object.authentication_secret.length;
    length += object.client_ip_addr.length;
    return length + 8;
  }

  static datatype() {
    // Returns string type for a message object
    return 'rll_msgs/JobEnvGoal';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '8914a2dc1274b4dcf064150662370a1c';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    string authentication_secret
    string client_ip_addr
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new JobEnvGoal(null);
    if (msg.authentication_secret !== undefined) {
      resolved.authentication_secret = msg.authentication_secret;
    }
    else {
      resolved.authentication_secret = ''
    }

    if (msg.client_ip_addr !== undefined) {
      resolved.client_ip_addr = msg.client_ip_addr;
    }
    else {
      resolved.client_ip_addr = ''
    }

    return resolved;
    }
};

module.exports = JobEnvGoal;
